### ISSUE TITLE
Sämtliche Links in PARK-Felder

### ISSUE THREAD

**Issue by oschihin** [swissbib/eadTransformations#1]
## Task

Aktuell wird bei Daten aus HelveticArchives nur ein Link in ein PARK-Feld (950) übertragen. Für Konsistenz und eine einfachere Konfiguration sollen alle Links in PARK-Feldern enthallten sein.
## Bemerkungen
- Beispiel: []/Record/cha83873
- hängt zusammen mit: https://github.com/swissbib/vufind/issues/289

**Comment by ToVie** [comment]
@oschihin Willst Du die URLs nur noch im PARK-Feld oder weiterhin parallel?

**Comment by oschihin** [comment]
@ToVie : gerne parallel

**Comment by ToVie** [comment]
@oschihin Ich habe mir die aktuelle Umsetzung angeschaut und würde entgegen deinem Wunsch wie folgt verfahren:

Ansichtsbild: 856 und 950
Vorschaubild: 950

Der Vorschaubildlink ist für Normalos wertlos, da er nur Datenmüll zurückliefert. Das Ansichtsbild liefert nutzerrelevante Infos und kommt deshalb als 856 und 950 vor.
Kannst Du damit umgehen oder wirft dir das alles durcheinander?

**Comment by oschihin** [comment]
In der Anzeigekonfiguration verwenden wir nur 950. Ich kann mit allem 
umgehen, solange im 950 ein Link zum Vorschaubild ist

Am 04.06.2015 um 12:31 schrieb ToVie:

> @oschihin https://github.com/oschihin Ich habe mir die aktuelle
> Umsetzung angeschaut und würde entgegen deinem Wunsch wie folgt verfahren:
> 
> Ansichtsbild: 856 und 950
> Vorschaubild: 950
> 
> Der Vorschaubildlink ist für Normalos wertlos, da er nur Datenmüll
> zurückliefert. Das Ansichtsbild liefert nutzerrelevante Infos und kommt
> deshalb als 856 und 950 vor.
> Kannst Du damit umgehen oder wirft dir das alles durcheinander?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/swissbib/eadTransformations/issues/1#issuecomment-108832582.

## 

UNIVERSITÄT BASEL
Universitätsbibliothek
Oliver Schihin
Projekt swissbib
Schönbeinstrasse 18-20
4056 Basel, Schweiz
Tel.: +41 61 267 13 07
Fax: +41 61 267 31 03
E-Mail oliver.schihin@unibas.ch
URL http://www.swissbib.org/

**Comment by ToVie** [comment]
Wichtig - das Vorschaubild dient nicht der Ansicht für den Benutzer sondern nur für die Darstellung des Vorschaubildes in swissbib.
Das Ansichtsbild zeigt dem Benutzer das Bild in einem Scope-Fenster:

Vorschaubild:  http://www.helveticarchives.ch/getimage.aspx?VEID=287281&DEID=10&SQNZNR=1&SIZE=10 
Ansichtsbild: http://www.helveticarchives.ch/bild.aspx?VEID=287281&DEID=10&SQNZNR=1&SIZE=10

**Comment by oschihin** [comment]
alles klar
1. Vorschaubild wird aus 950 gebildet
2. Link zum Ansichtsbild auch aus 950
Der Issue bezieht sich darauf, dass ich mit der neuen Konfiguration (https://github.com/swissbib/vufind/blob/73eb8735ca3d1c727719f5b70c1c48ef616c0845/module/Swissbib/src/Swissbib/View/Helper/Record.php#L50) Links nur noch aus 950 und 956 beziehe. (Liesse sich natürlich anders konfigurieren.) Aber eben, deshalb beide Links im 950 (den Link zum Vorschaubild muss ich dann für die Anzeige wieder "wegkonfigurieren").

**Comment by ToVie** [comment]
@oschihin das ist richtig. Wenn es Dir dient, kann ich den Vorschaulink auch in ein 956-Feld zügeln, dann musst Du im 856-er Bereich nichts wegkonfigurieren.

Ich kann Dir dann auch gleich die neu transformierten MarcXML-Dateien schicken...

**Comment by oschihin** [comment]
Super

Am 04.06.2015 um 14:26 schrieb ToVie:

> @oschihin https://github.com/oschihin das ist richtig. Wenn es Dir
> dient, kann ich den Vorschaulink auch in ein 956-Feld zügeln, dann musst
> Du im 856-er Bereich nichts wegkonfigurieren...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/swissbib/eadTransformations/issues/1#issuecomment-108872036.

## 

UNIVERSITÄT BASEL
Universitätsbibliothek
Oliver Schihin
Projekt swissbib
Schönbeinstrasse 18-20
4056 Basel, Schweiz
Tel.: +41 61 267 13 07
Fax: +41 61 267 31 03
E-Mail oliver.schihin@unibas.ch
URL http://www.swissbib.org/
